# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Projekty"
  pageRef = "Projekty"
  weight = 10

[[main]]
  name = "O Mně"
  pageRef = "posts/O Mně"
  weight = 20

[[main]]
  name = "Projekt 1 - Webstránka"
  parent = "Projekty"
  pageRef = "posts/Projekt 1 - Webstránka"
  weight = 10

[[main]]
  name = "Projekt 2 - 2D grafika a řezání"
  parent = "Projekty"
  pageRef = "posts/Projekt 2 - 2D grafika a řezání"
  weight = 10

[[main]]
  name = "Projekt 3"
  parent = "Projekty"
  pageRef = "Projekty/Projekt 3"
  weight = 10

  [[main]]
  name = "Projekt 4"
  parent = "Projekty"
  pageRef = "Projekty/Projekt 4"
  weight = 10

  [[main]]
  name = "Projekt 5"
  parent = "Projekty"
  pageRef = "Projekty/Projekt 5"
  weight = 10

  [[main]]
  name = "Finální Projekt"
  parent = "Projekty"
  pageRef = "posts/Finální Projekt"
  weight = 10
#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
